### ISSUE TITLE
doesn't build properly 

### ISSUE THREAD

**Issue by iapicca** [acaliaro/flutterZebraEmdk#1]
The project doesn't run,
`
* * Error running Gradle:
ProcessException: Process "C:\Users\iapic\OneDrive\Desktop\Code\notMine\flutterZebraEmdk\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)
BUILD FAILED
Total time: 15.935 secs
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
'
and so on... 
does it work for you?
how did you manage to import the jar? doesn't seems being gradle based

**Comment by acaliaro** [comment]
Hi @iapicca 

I am able to build the apk. Is your Android Studio updated?

I suggest also not to use EMDK if you have only to scan barcodes. Use DataWedge API: http://techdocs.zebra.com/datawedge/6-3/guide/api/

**Comment by Freundschaft** [comment]
@iapicca check out this https://github.com/acaliaro/flutterZebraEmdk/pull/3 and tell me if it works

**Comment by DiogoMoreira0610** [comment]
Hi @acaliaro,

You have any sample to do this with flutter?

**Comment by acaliaro** [comment]
this is with flutter

**Comment by DiogoMoreira0610** [comment]
Ops... with datawedge

Em seg, 27 de mai de 2019 10:54, Alessandro Caliaro <
notifications@github.com> escreveu:

**Comment by acaliaro** [comment]
DataWedge is more simple than EMDK. You can use Intents… [http://www.darryncampbell.co.uk/2018/01/03/tutorial-the-datawedge-intent-api/](http://www.darryncampbell.co.uk/2018/01/03/tutorial-the-datawedge-intent-api/)

**Comment by iapicca** [comment]
closing as the issue is not anymore relevant
since flutter changed the embedding for native plugins
