### ISSUE TITLE
Implement Common App for Non-Zebra Devices

### ISSUE THREAD

**Issue by Freundschaft** [acaliaro/flutterZebraEmdk#4]
Is it possible to integrate this approach to this project?

http://techdocs.zebra.com/emdk-for-android/4-0/guide/programming_practices/#creatingacommonapplicationtorunonzebraandnonzebradevices

**Comment by acaliaro** [comment]
Yes, why not? You can do what you want in the "Android" native project.

**Comment by Freundschaft** [comment]
yes, I know, but I meant more like, to integrate it in this project as an example :)

**Comment by alexsauce** [comment]
I'm interested on this too, I was able to make it work, but now I can't run my code in the emulator, because it can't find the package:
**Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Package couldn't be installed in /data/app/com.example.wimflutter-tJTxBgaYIaZF5Z7Z5bp32g==: Package com.example.wimflutter requires unavailable shared library com.symbol.emdk; failing!]**

**Comment by acaliaro** [comment]
I don't know if you can use it on an emulator because it has not the EMDK installed. I think you have to use a real Zebra device

**Comment by leedaga** [comment]
> Package com.example.wimflutter requires unavailable shared library com.symbol.emdk; failing!]

me too, I don't know how to fix it.

**Comment by acaliaro** [comment]
Hi. I suggest you not to use EMDK to scan barcodes with Zebra Devices. Zebra suggests to use INTENTS.... You have to use EMDK only if you need to use "profiles".

**Comment by acaliaro** [comment]
> Package com.example.wimflutter requires unavailable shared library com.symbol.emdk; failing!]
> 
> me too, I don't know how to fix it.

Are you using a Zebra device to test your app?

**Comment by leedaga** [comment]
yes, it's a MC36 of zebra.

**Comment by leedaga** [comment]
> Hi. I suggest you not to use EMDK to scan barcodes with Zebra Devices. Zebra suggests to use INTENTS.... You have to use EMDK only if you need to use "profiles".

OK , I will try it,TKS !

**Comment by darryncampbell** [comment]
The Zebra MC36 device is a special case as it did not technically ever support the EMDK.  This will be why the MC36 does not work with this module.

**Comment by acaliaro** [comment]
> The Zebra MC36 device is a special case as it did not technically ever support the EMDK.  This will be why the MC36 does not work with this module.

Wow @darryncampbell !!! this is an honor

**Comment by darryncampbell** [comment]
> > The Zebra MC36 device is a special case as it did not technically ever support the EMDK.  This will be why the MC36 does not work with this module.
> 
> Wow @darryncampbell !!! this is an honor

haha thanks.  We are starting to get quite a few questions on Flutter and I usually point them towards this project.  Flutter doesn't seem to have a Intent mechanism flexible enough to integrate well with DataWedge unfortunately, even looking at what is available from 3rd party packages.

**Comment by acaliaro** [comment]
> The Zebra MC36 device is a special case as it did not technically ever support the EMDK.  This will be why the MC36 does not work with this module.
> 
> Wow @darryncampbell !!! this is an honor
> 
> haha thanks.  We are starting to get quite a few questions on Flutter and I usually point them towards this project.  Flutter doesn't seem to have a Intent mechanism flexible enough to integrate well with DataWedge unfortunately, even looking at what is available from 3rd party packages.

@darryncampbell are you sure about " Flutter doesn't seem to have a Intent mechanism flexible"? Flutter "under the hood" use Android, so I think you can use Intent in Android Project (like I use EMDK in Android project) then send the data received from the broadcastreceiver to flutter using EventChannel

**Comment by darryncampbell** [comment]
> @darryncampbell are you sure about " Flutter doesn't seem to have a Intent mechanism flexible"? Flutter "under the hood" use Android, so I think you can use Intent in Android Project (like I use EMDK in Android project) then send the data received from the broadcastreceiver to flutter using EventChannel

Thanks for the tip, I think that is probably the best approach.  Typically our developers who use cross platform frameworks aren't comfortable modifying the java source so I was looking for an entirely Dart solution.  I didn't want to produce a generic flutter module for Android Intents but creating a Java class that interfaces between flutter and DataWedge is a good compromise.  Thanks again for the idea.

**Comment by darryncampbell** [comment]
First draft of a Flutter demo application that uses DataWedge is now at https://github.com/darryncampbell/DataWedgeFlutter.  Hopefully this issue can now be closed.  I'm not certain on the DataWedge version on MC36 but it should work, perhaps with a few tweaks.

**Comment by acaliaro** [comment]
excellent @darryncampbell. I add a link to your repo on my Readme
